### ISSUE TITLE
docker image

### ISSUE THREAD

**Issue by zhujisheng** [da-anda/hass-io-addons#11]
It would be nicer and faster, if you can build the docker image:
https://developers.home-assistant.io/docs/add-ons/publishing#build-scripts-to-publish-add-ons-to-docker-hub

**Comment by da-anda** [comment]
it would, but I'm on Windows and not Linux. Gave it a try once in a Linux VM and failed. It also took ages to build since I have all my data on a network share (aka file server with daily backups). So in the end I gave up on it since my spare time is limited these days.
