### ISSUE TITLE
USB path changes after restarts

### ISSUE THREAD

**Issue by JaccoR** [da-anda/hass-io-addons#15]
Hey, i am using the KNXd addon for home assistant quite a lot and it is the fundamental for my complete smarthouse. Thanks!

When i restart my raspberry pi with Home Assistant OS, the path to the knxd bus changes (`/dev/bus/usb/001/*`). This means i have to manually select the right usb path everytime i restart, because the automatic selecting does not work for me.

I guess this is a linux thing and you should be able to use udev rules to fix this, but udev rules aren't possible for Home Assistant OS.

**Comment by da-anda** [comment]
is there no `/dev/.../by-id/...` entry for your USB device? If not, try to leave it empty so that knxd does some autodetection.

**Comment by JaccoR** [comment]
![Screenshot_20211109-132604.png](https://user-images.githubusercontent.com/31140879/140924047-afd78b34-913e-4815-87b9-874613c2f58d.png)

I found these, but i am not sure what the part 1 etc. means. When selecting this device i get the error: `ERROR (SyncWorker_4) [supervisor.docker.addon] Add-on KNXD daemon try to access to blocked device mmcblk0!` from the supervisor and it doesn't work.

Autodetection does not work for me unfortunately. (Not sure why)

**Comment by da-anda** [comment]
I am not a Linux expert myself, but the error sounds like it might try to
access a partition of a HDD/SSD/sdcard. Do you have any usb attached
harddrive? Also, make sure you pick the correct "by-id" device, since not
only USB devices have such a path but also harddrives, serial devices etc

JaccoR ***@***.***> schrieb am Di., 9. Nov. 2021, 13:33:

**Comment by da-anda** [comment]
Ah sorry, the screenshot hadn't loaded in the notification email before
replied. Yes, those are wrong and references to the partitions of your
harddrive/storage. The path needs to have "/usb/" in it

JaccoR ***@***.***> schrieb am Di., 9. Nov. 2021, 13:33:

**Comment by JaccoR** [comment]
Ah okay, well these are the only "by-id" i have listed there.

**Comment by da-anda** [comment]
too bad. My TPUART USB stick shows up as `/dev/serial/by-id/.....` as well as on the according USB port. So I suspected that yours might as well show up somehwere with a `by-id` path. And it doesn't work if you leave the device selector empty (aka forcing knxd to autodetect the device to use)?

**Comment by JaccoR** [comment]
I am using a KNX USB interface, not a TPUART USB stick. So maybe that is why it does not show up on that path. There is no other path than /dev/bus/usb/001/*for the USB interface.

**Comment by da-anda** [comment]
I know. But since the OS is assigning the USB device to whatever internal port and not the add-on, I doubt that I can do anything to fix the issue on my end. But I'm no linux crack, nor very good with docker. So if there is anything I can do, let me know.

**Comment by JaccoR** [comment]
Alright, thanks for your help! I'll try to figure it out when I have time and come back to you.
