### ISSUE TITLE
cannot save configuration after upgrade to 4.4.4

### ISSUE THREAD

**Issue by tobiaskitsune** [da-anda/hass-io-addons#18]
Hello,

after update of KNXD from 4.4.2 to 4.4.4 my configuration does not work any longer. When I try to save a configuration I get the following error.

`Fehler beim Speichern der Add-on-Konfiguration, expected int. Got {'address': '0.0.1', 'client_address': '0.0.2:8', 'interface': 'usb', 'device': '/dev/bus/usb/001/001', 'log_error_level': 'warning', 'usb_filters': 'single', 'ip_address': '', 'dest_port': '', 'custom_config': ''}`

The following error I get when I try to start KNXD

`expected int.`

All was running fine with KNXD 4.4.2.

I am using:
- Core Version core-2022.4.3
- Supervisor Version supervisor-2022.04.0
- Home Assistant OS 7.6

**Comment by da-anda** [comment]
yeah, for some reason HA doesn't respect my configuration for the optional `port` setting, and the error message is not helpful at all (in fact, any validation error message is nowhere near helpful).

So for the time being, you have to add any number > 0 in the `Interface port` config option.

Sorry for that, but I didn't want to push a fix, as it would have triggered a new build on github which wouldn't be necessary for this fix. I still need to figure out how to best handle these automated builds.

**Comment by da-anda** [comment]
should hopefully be fixed now for other people that update. You, unfortunately have to change the default value of that option manually.

**Comment by tobiaskitsune** [comment]
Yes, with changes port number it is working.
