### ISSUE TITLE
KNXD not working ABB USB/S1.2

### ISSUE THREAD

**Issue by berhankanbur** [da-anda/hass-io-addons#22]
Hello. First of all, sorry for my bad english. I installed homeassistant supervised on my Orange Pi PC Plus device via debian.

I'm trying to use KNXD but when I send value via ETS 5, I get ''F00000105: [15:interface-usb] Link down, terminating'' error.

I think there are a few solutions in the forum, but I could not solve it because I do not have enough knowledge.

Thanks for help.

**Comment by berhankanbur** [comment]
My config is like this

![Capture](https://user-images.githubusercontent.com/64873540/169326268-750c9015-e91c-4e02-8ccd-8fa3a1f20654.PNG)

**Comment by da-anda** [comment]
Hi. No need to apologize for your English, it is perfectly fine. Unfortunately I can not really help in regards of the correct configuration of KNXD for your particular USB interface, since I have 0 knowledge of the inner workings of KNXD or what exactly could cause the connection to be terminated.

If you selected the correct USB device in the drop down, it should get recognized by knxd. Depending on the USB device, you might need custom `usb_filters` settings, but I have no idea which ones, sorry. It's probably try and error at this point.
I would suggest to ask on the forum, maybe someone is using the same USB interface as you and can give you the correct filter settings. Or have you tried googling for `knxd ABB USB/S1.2 issue`?

And is the connection working at all, like do you see your KNX devices in HomeAssistant and only ETS is causing the connection to break up, or is it broken in general?

**Comment by da-anda** [comment]
by googling I just came across this bug report over at knxd, which sounds a bit like your problem
https://github.com/knxd/knxd/issues/517

**Comment by berhankanbur** [comment]
> > googling yaparak knxd'de bu hata raporuna rastladım, bu biraz sizin probleminize [benziyor knxd/knxd#517](https://github.com/knxd/knxd/issues/517)
> 
> Yes, I reviewed that. I think I have reached the solution, but because my English is poor, I did not understand it with translation. A patch has been shared but I have no idea how to install it.

The problem doesn't seem to be similar. I only get "link down terminating" error in my logs.

**Comment by berhankanbur** [comment]
> Hi. No need to apologize for your English, it is perfectly fine. Unfortunately I can not really help in regards of the correct configuration of KNXD for your particular USB interface, since I have 0 knowledge of the inner workings of KNXD or what exactly could cause the connection to be terminated.
> 
> If you selected the correct USB device in the drop down, it should get recognized by knxd. Depending on the USB device, you might need custom `usb_filters` settings, but I have no idea which ones, sorry. It's probably try and error at this point. I would suggest to ask on the forum, maybe someone is using the same USB interface as you and can give you the correct filter settings. Or have you tried googling for `knxd ABB USB/S1.2 issue`?
> 
> And is the connection working at all, like do you see your KNX devices in HomeAssistant and only ETS is causing the connection to break up, or is it broken in general?

KNX Konfigürasyonunu homessistant'ta oluşturdum cihazları ekledim, fakat hiç bir şekilde knx ile haberleşemiyorum.

**Comment by berhankanbur** [comment]
![Capture](https://user-images.githubusercontent.com/64873540/169354421-6f8daef3-4ace-47ca-bc0c-7de53675ee00.PNG)

**Comment by da-anda** [comment]
ok, so the communication doesn't work at all and it is not just terminating when ETS is trying to use it.

As for the patch in the linked PR. You can not apply this patch yourself. I would have to apply it to the source code of knxd and then build a new version of the add-on. Or, well, you compile your own version of knxd ofc

**Comment by berhankanbur** [comment]
> ok, so the communication doesn't work at all and it is not just terminating when ETS is trying to use it.
> 
> As for the patch in the linked PR. You can not apply this patch yourself. I would have to apply it to the source code of knxd and then build a new version of the add-on. Or, well, you compile your own version of knxd of course

I guess there's nothing I can do right now. You said try a filter, where can I find the filters I need to try?

**Comment by da-anda** [comment]
Here is the official documentation: https://github.com/knxd/knxd/blob/main/doc/inifile.rst#filters

**Comment by da-anda** [comment]
oh, and if you happen to run Linux on your pc/laptop, it might be easier to debug things if you plug your USB interface to your linux PC, install knxd there and try to get it running there first (by testing different configurations etc via command line arguments). 
Since I am no knxd expert by any means, I unfortunately can not give more technical help on this. I only managed to create an add-on for knxd (by using google a lot), got it to work with my TPUART interface and though I'd share my add-on in case it is of use for others. But I am not very good with anything linux myself

**Comment by berhankanbur** [comment]
Thanks for you help

**Comment by berhankanbur** [comment]
No one helped but you. I am so desperate :)

**Comment by berhankanbur** [comment]
> oh, and if you happen to run Linux on your pc/laptop, it might be easier to debug things if you plug your USB interface to your linux PC, install knxd there and try to get it running there first (by testing different configurations etc via command line arguments). Since I am no knxd expert by any means, I unfortunately can not give more technical help on this. I only managed to create an add-on for knxd (by using google a lot), got it to work with my TPUART interface and thought I'd share my add-on in case it is of use for others. But I am not very good with anything linux myself

Hey daanda how are you?

After three days of research, I think I found something. On a forum it says if I increase the "sendtimeout" setting to 5000 it will fix the problem. How to do this setting, I would be very happy if you can help.

**Comment by da-anda** [comment]
in order to not bloat the settings screen even more with all configuration options knxd provides, not everything is configurable via these settings and instead uses sane defaults that should work for most users. The `sendtimeout` is already increased to 3000 in the default configuration of the add-on. If you would like to set it even higher you would have to provide a custom configuration to the add-on. Unfortunately the GUI wizard of HomeAssistant does no longer allow multi-line input, so that you have to switch the configuration of the add-on to YAML (use the `edit as YAML` option in the context menu that shows up when you click the dotted line in the upper right corner of the configuration page).

Then replace `custom_config: ''` with the following:
```
custom_config: |
  [main]
  addr = 0.0.1
  client-addrs = 0.0.2:10
  connections = server,A,tcp,interface-usb
  logfile = /dev/stdout
  debug = debug
  
  [A.tcp]
  server = knxd_tcp
  
  [server]
  server = ets_router
  tunnel = tunnel
  router = router
  discover = true
  name = knxd
  
  [debug]
  error-level = warning
  
  [interface-usb]
  driver = usb
  device = 2
  bus = 7
  filters = single,queue
  send-timeout = 5000
```
You can add any other config option from knxd in the last section `interface-usb`, or, ofc change anything else in this custom configuration

**Comment by berhankanbur** [comment]
> in order to not bloat the settings screen even more with all configuration options knxd provides, not everything is configurable via these settings and instead uses sane defaults that should work for most users. The `sendtimeout` is already increased to 3000 in the default configuration of the add-on. If you would like to set it even higher you would have to provide a custom configuration to the add-on. Unfortunately the GUI wizard of HomeAssistant does no longer allow multi-line input, so that you have to switch the configuration of the add-on to YAML (use the `edit as YAML` option in the context menu that shows up when you click the dotted line in the upper right corner of the configuration page).
> 
> Then replace `custom_config: ''` with the following:
> 
> ```
> custom_config: |
>   [main]
>   addr = 0.0.1
>   client-addrs = 0.0.2:10
>   connections = server,A,tcp,interface-usb
>   logfile = /dev/stdout
>   debug = debug
>   
>   [A.tcp]
>   server = knxd_tcp
>   
>   [server]
>   server = ets_router
>   tunnel = tunnel
>   router = router
>   discover = true
>   name = knxd
>   
>   [debug]
>   error-level = warning
>   
>   [interface-usb]
>   driver = usb
>   device = 2
>   bus = 7
>   filters = single,queue
>   send-timeout = 5000
> ```
> 
> You can add any other config option from knxd in the last section `interface-usb`, or, ofc change anything else in this custom configuration
> 
> edit: this custom configuration will replace everything you configured via the UI. So whatever you had configured before will be ignored. I tried to already use the correct values for the USB device and bus for your setup (based on your screenshots). Hope it works. If not and the USB-ID of the device has changed, you will have to adjust the numbers in the interface-usb section accordingly.
> 
> Please let me know if the timeout of 5000 fixes your issue. If so, I will update the default setting of the add-on to 5000

No, unfortunately that didn't solve my problem either. I think I'm going to give up, there is no way I haven't tried.

I tried to install Calimero and eibd on linux, but I was not successful in that either. I can't communicate with knx in any way.

**Comment by berhankanbur** [comment]
> by googling I just came across this bug report over at knxd, which sounds a bit like your problem [knxd/knxd#517](https://github.com/knxd/knxd/issues/517)

Hello again daanda. This issue was the same as mine. I noticed when I added the -log- command.

But I have no idea how to do the solution there, I don't understand what it does. Give it to my linux ignorance :).

**Comment by da-anda** [comment]
you would have to compile knxd with the patch applied yourself as there is no way I could easily provide an add-on version with this patch in just for you and without risking to break the add-on for other users due to this patch.

**Comment by da-anda** [comment]
@berhankanbur ok, so I went the extra mile, forked knxd, applied the patch and created a new BETA repository for my add-on in which you can test the changes. Please add this https://github.com/da-anda/hass-io-addons-beta as add-on repository in HomeAssistant and try version 0.4.5 from there (once it finished building the add-ons as I pushed the changes just this second)

**Comment by berhankanbur** [comment]
![daanda](https://user-images.githubusercontent.com/64873540/169691792-321450e7-fe0f-44a5-896d-8ff778bf4fd7.png)
I'm getting this error while installing the beta.

**Comment by da-anda** [comment]
it is not compiled yet. Seems the new repo has some issues

**Comment by berhankanbur** [comment]
> henüz derlenmemiş. Yeni deponun bazı sorunları var gibi görünüyor

will you solve?

**Comment by da-anda** [comment]
no idea since I have no idea why github fails to compile it. This is all new territory for me

**Comment by berhankanbur** [comment]
> no idea since I have no idea why github fails to compile it. This is all new territory for me

I understand. I will be very happy if you can solve it.

**Comment by da-anda** [comment]
please try again, it seems they built now

**Comment by berhankanbur** [comment]
> please try again, it seems they built now
Unfortunately, this time the broadcast did not start.

![knxdlog](https://user-images.githubusercontent.com/64873540/169696030-b12e9f21-571a-46fa-b04d-15c5a9e59466.PNG)

**Comment by da-anda** [comment]
sorry, doesn't ring any bell. No idea what's going on there. Nothing changed in the file `2-init-config` since version 0.4.4. Maybe it's an issue with your configuration now? Please remove the custom configuration if you still have it in there

**Comment by berhankanbur** [comment]
No, there is no special configuration. I deleted the old knxd and installed this.

**Comment by berhankanbur** [comment]
> sorry, doesn't ring any bell. No idea what's going on there. Nothing changed in the file `2-init-config` since version 0.4.4. Maybe it's an issue with your configuration now? Please remove the custom configuration if you still have it in there

Where you able to fix?

**Comment by da-anda** [comment]
no. I also have other things to do, you know ;)
I think you are better of trying https://github.com/aschamberger/hassio-addons/tree/master/calimero-server

**Comment by da-anda** [comment]
I just tested the changes compiling the add-on locally on my PI and I don't get the error. When I use the version from the beta repository, I get the same error as you do in your screenshot. No idea what went wrong on github when it built the add-on image. 

So I disabled pre-compiled github images, which means, once you install it, it will try to compile knxd directly on your device, and this can take up to 20 min or longer. So be patient. You might have to uninstall 0.4.5 first, if HomeAssistant is showing an error message that it can't install the update

**Comment by berhankanbur** [comment]
> I just tested the changes compiling the add-on locally on my PI and I don't get the error. When I use the version from the beta repository, I get the same error as you do in your screenshot. No idea what went wrong on github when it built the add-on image.
> 
> So I disabled pre-compiled github images, which means, once you install it, it will try to compile knxd directly on your device, and this can take up to 20 min or longer. So be patient. You might have to uninstall 0.4.5 first, if HomeAssistant is showing an error message that it can't install the update
![Capture](https://user-images.githubusercontent.com/64873540/169714638-12f79251-ceb9-421b-a963-ab846ec82422.PNG)

Unfortunately, this time this was given. I installed it by removing the previous knxd.

I didn't know that Calimeron was in the hass add-on, but of course my system is incompatible!. ARMv8 is required.

I tried to install Calimero and eibd on linux but without success. There are not enough articles that I can understand.

**Comment by berhankanbur** [comment]
> I just tested the changes compiling the add-on locally on my PI and I don't get the error. When I use the version from the beta repository, I get the same error as you do in your screenshot. No idea what went wrong on github when it built the add-on image.
> 
> So I disabled pre-compiled github images, which means, once you install it, it will try to compile knxd directly on your device, and this can take up to 20 min or longer. So be patient. You might have to uninstall 0.4.5 first, if HomeAssistant is showing an error message that it can't install the update

I tested version 4.5.5 and 4.5.5a via local repository.

I still get the same errors, in 4.5.5 the server does not start, in 4.5.5a it is not installed at all.

**Comment by berhankanbur** [comment]
Hello again da-anda.
With the help of a script I installed calimero on debian and my problem is solved, I can communicate with knx.

Thank you for your efforts, I tired you a lot :)
