### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by mechanliang** [da-anda/hass-io-addons#28]
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 2-init-config: executing... 
[22:04:37] INFO: Interface:      tpuart
[22:04:37] INFO: Device:         /dev/ttyUSB0
[22:04:37] INFO: Address:        0.0.1
[22:04:38] INFO: Client Address: 0.0.2:8
[22:04:38] INFO: Filters:        single
[22:04:38] INFO: Log-Level:      warning
[22:04:39] INFO: IP-Address:     
[22:04:39] INFO: Dest-Port:      99
[cont-init.d] 2-init-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
F00000105: [15:interface-tpuart] Link down, terminating
F00000105: [15:interface-tpuart] Link down, terminating
F00000105: [15:interface-tpuart] Link down, terminating
F00000105: [15:interface-tpuart] Link down, terminating
F00000105: [15:interface-tpuart] Link down, terminating
F00000105: [15:interface-tpuart] Link down, terminating
F00000105: [15:interface-tpuart] Link down, terminating
F00000105: [15:interface-tpuart] Link down, terminating
F00000105: [15:interface-tpuart] Link down, terminating
F00000105: [15:interface-tpuart] Link down, terminating
F00000105: [15:interface-tpuart] Link down, terminating
F00000105: [15:interface-tpuart] Link down, terminating
F00000105: [15:interface-tpuart] Link down, terminating
F00000105: [15:interface-tpuart] Link down, terminating
F00000105: [15:interface-tpuart] Link down, terminating
F00000105: [15:interface-tpuart] Link down, terminating
F00000105: [15:interface-tpuart] Link down, terminating
F00000105: [15:interface-tpuart] Link down, terminating
F00000105: [15:interface-tpuart] Link down, terminating
F00000105: [15:interface-tpuart] Link down, terminating
F00000105: [15:interface-tpuart] Link down, terminating
F00000105: [15:interface-tpuart] Link down, terminating
F00000105: [15:interface-tpuart] Link down, terminating
F00000105: [15:interface-tpuart] Link down, terminating
F00000105: [15:interface-tpuart] Link down, terminating
F00000105: [15:interface-tpuart] Link down, terminating

**Comment by mechanliang** [comment]
This is the case with tpuart2 and ncn5120 or ncn5121

**Comment by da-anda** [comment]
which interface are you using? And have you tried to use your interface via a locally running knxd version? I can't really give support on which interface needs which configuration to work with knxd since I am not a developer of knxd, nor do I have any inside knowledge of it.

**Comment by da-anda** [comment]
@mechanliang did you make any progress?

**Comment by da-anda** [comment]
@mechanliang any update on this? Is the issue fixed in the most recent version of the add-on (and knxd for that matter)?
