### ISSUE TITLE
Opening /dev/ttyACM0 failed: No such file or directory

### ISSUE THREAD

**Issue by lukaszolek** [da-anda/hass-io-addons#3]
Hi,
I tried your addon to run knxd daemon on hass.io installation (previously I had a hasspbian installation with knxd on the same hardware and it worked fine) - Raspberry Pi 4 + Gira USB interface.

Unfortunately, it doesn't start.
With the default configuration, after running start I get the following lines in my log, and the starting fails:
```
E00000067: [15:interface] Opening /dev/ttyACM0 failed: No such file or directory
F00000105: [12:interface] Link down, terminating
```

After changing the config to:
```
{
  "address": "0.0.1",
  "client_address": "0.0.1:10",
  "interface": "usb",
  "device": "/dev/ttyACM0",
  "custom_config": ""
}
```

I get: 
```
E00000040: [15:interface] USBLoop-Create: No such file or directory
E00000103: [15:interface] setting up USB failed
E00000064: [12:interface] interface: setup interface: failed
F00000109: [ 1:main] Error setting up the KNX router.
```

I even tried to make a fork of your addon to add:
  "devices": ["/dev/ttyAMA0:/dev/ttyAMA0:rwm"] to the config.json
(I thought the docker doesn't have access to the RPI devices), but it also didn't work.

What am I missing?

**Comment by palhaland** [comment]
@lukaszolek if you try version 0.3.2 then it should be possible to use the Gira USB interface, to be able to transmit packets to the bus, you might also need some extra configuration, have a look in post: https://community.home-assistant.io/t/knxd-add-on-covert-your-knx-usb-interface-into-an-ip-interface-that-can-be-used-by-ha/38108/55?u=palhaland

but please try first without that extra config.
