### ISSUE TITLE
Duplicated telegrams, probably missing acknowledge

### ISSUE THREAD

**Issue by arnonym** [da-anda/hass-io-addons#33]
First of all: thank you for providing this add-on!

In the bus monitor in ETS I can see duplicated telegrams from devices that send data only to home-assistant (no other knx device is assigned to the group):

![image](https://user-images.githubusercontent.com/89100/201308301-a8228fb0-39af-46df-a905-b9bc499c31b7.png)

I'm using the TPUART from busware.

I wonder if these telegrams should be acknowledged by knxd? As you're also using the same USB dongle, do you also have that problem?

**Comment by da-anda** [comment]
yes, I also see these yellow telegrams if you mean those

**Comment by arnonym** [comment]
These are retries because of a missing acknowledge. I would like to get rid of them to keep the bus traffic low. Is the wind-speed group address read by another knx device?

I could get rid of them by removing the "single" usb-filter. Not sure if there is any down-side to this, but everything seems to work as expected. Also my knx power supply stopped blinking the "bus error" LED.

**Comment by da-anda** [comment]
no, windspeed and all other sensor values of my weather station are only read by HA, no other devices (HA is the only device in the GA, along with the sender).

The filter "single" should only apply to USB interfaces, not your Busware TPUART interface

**Comment by arnonym** [comment]
I had configured the interface in ETS manually with a faulty device address. Now using the auto-detected interface and the problem without using "single" is gone now. :see_no_evil:

The retries are only happening now when HA is reading all the states and the bus load is greater than 80%.

So all good now. Thanks for the help!
