### ISSUE TITLE
libusb: error [get_usbfs_fd] libusb couldn't open USB device /dev/bus/usb/002/005, errno=1

### ISSUE THREAD

**Issue by ct991218620** [da-anda/hass-io-addons#34]
“interface driver” choose “usb” and “device to use for connection”  choose  “/dev/usb/hiddev0”  will  report errors “libusb: error [get_usbfs_fd] libusb couldn't open USB device /dev/bus/usb/002/005, errno=1”

**Comment by da-anda** [comment]
are you sure this is the correct USB device? Have you tried not to specify a USB device and have knxd use auto-discover? Other than that, I can't really help with this. I am not a knxd developer. What you could try is to see if your USB KNX interface is working with knxd at all by installing knxd locally on your device (or by using a VM if you are on Windows) and play around with different startup parameters. If it also doesn't work there, there is nothing I can do. But if it does, tell me which configuration you needed to get it to work with knxd and I am happy to adjust the add-on accordingly.

**Comment by ct991218620** [comment]
> were you able to resolve your issue, or did you give up? If you were able to resolve it, mind sharing how you fixed it in case others run into a similar issue? Thanks.

yes , i have resolved it ,add  "usb:true" in to file "config:yaml" .

**Comment by ct991218620** [comment]
> were you able to resolve your issue, or did you give up? If you were able to resolve it, mind sharing how you fixed it in case others run into a similar issue? Thanks.

yes,i have resolved it ,add "usb:true" in to file "config.yaml".

**Comment by da-anda** [comment]
thanks for the info, will add it in the next release
