### ISSUE TITLE
KNXD stops with error: Link down, terminating.

### ISSUE THREAD

**Issue by lukaszolek** [da-anda/hass-io-addons#4]
My KNXD daemon works for several hours, and suddenly stops with following messages in the log:
```
F00000108: [15:interface] Send while buffer not empty
F00000105: [12:interface] Link down, terminating
E00000035: [15:interface] SendError 1f7ad70 status 3
```
Do you know why?
Any suggestions what to do? 
Thanks!

**Comment by lukaszolek** [comment]
Every 1-2 days I observe mentioned problem that causes the knxd addon to stop. When it occurs, I need to start it manually. Do you know how to change the knxd addon to restart automatically after failure?

**Comment by da-anda** [comment]
odd that I didn't get any notifications on your issue. So my apologies for not responding earlier. But sorry, no idea what that could be.

**Comment by palhaland** [comment]
@lukaszolek if you are using a USB device, then you can try with the configuration in: https://community.home-assistant.io/t/knxd-add-on-covert-your-knx-usb-interface-into-an-ip-interface-that-can-be-used-by-ha/38108/55?u=palhaland and see if that solves the issue. I had the same issues, and that solved it for me. (I tried to make a pull request to add the filter functions, but apparently that didn't work) Currently you need to use the custom function

**Comment by da-anda** [comment]
Please reopen if you still have issues.
