### ISSUE TITLE
32 bit docker image

### ISSUE THREAD

**Issue by georgegougoudis** [da-anda/hass-io-addons#54]
I'm running the addon on a raspberry pi2 which I think is 32 bit.

Getting the error:
`exec /init: exec format error`

Pretty sure this happens because the container/knxd is 64bits.

Is it possible to provide a container for 32bits too?

**Comment by da-anda** [comment]
as far as I know, for RPI2 there only is the `armhf` image available (https://github.com/home-assistant/docker-base), and that is what this add-on uses. AFAIK `armhf` is 32bit only, and I think I started this add-on on a RPI2 and it was at least working back then. No idea about its current state though as i am unable to test (my linux skills are basic and I am already glad that I got this add-on as far as it is at the moment)

**Comment by da-anda** [comment]
can this issue be closed, or are you still looking for a 32bit docker image?

**Comment by georgegougoudis** [comment]
I've managed to create a custom image for my needs, all my other PI's are 64 bit so I've solved my issue.
