### ISSUE TITLE
Logs inaccessible since 0.5.2 Update

### ISSUE THREAD

**Issue by DarrolMusambani** [da-anda/hass-io-addons#63]
Log tab shows error message:
`Failed to get ecaeb50e_knxd logs, e.callApiRaw is not a function`

**Comment by da-anda** [comment]
sounds more like an issue with the Supervisor as the add-on itself does not have special logic for log files (these are all handled by the supervisor). Maybe an update has not yet fully finished. Wait a couple mins and try again, or try to reinstall

**Comment by da-anda** [comment]
ah, I also get this error now, but on any of the add-ons, so it is certainly not specific to this add-on.

**Comment by da-anda** [comment]
you might have to update HomeAssistant and/or clear your browser cache. I did both and the error of the supervisor is gone now

**Comment by DarrolMusambani** [comment]
Hi, I also just noticed this is related to the supervisor.
Sorry for this false alarm.
