### ISSUE TITLE
Multicasting does not seem to work

### ISSUE THREAD

**Issue by stemnic** [da-anda/hass-io-addons#9]
I have a raspberrypi 3 running Hassos which i used knxd with. I noticed that I had problems using the multicast function of knxd. After adding "host_network": true, under config.json this seemed to be resolved. Any reason why this addon is not has the host network bridged?

https://developers.home-assistant.io/docs/add-ons/configuration

**Comment by da-anda** [comment]
no particular reason - just missing knowledge. Would you like to create a PR?
